[toolchain]
anchor_version = "0.32.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
# These IDs must match your declare_id! in Rust
placeholder_bank = "J5juVUkDeUwb3rXT1saab2q87aXyBjzmuAZ7dhMCfbka" 
placeholder_engine = "2JfW8D59eJ1myVbqpU8BBLxkWp3Bhwf6yjY8HfuqBSHv"

[programs.devnet]
placeholder_bank = "J5juVUkDeUwb3rXT1saab2q87aXyBjzmuAZ7dhMCfbka"
placeholder_engine = "2JfW8D59eJ1myVbqpU8BBLxkWp3Bhwf6yjY8HfuqBSHv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet" # Change to "https://devnet.magicblock.app" for MagicBlock Testnet
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
